# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q_e1q3gG2Aws7gTE5fP55VHNvRh6daKl
"""

import hashlib
a="Good Morning"
b=hashlib.md5(a.encode('utf-8')).hexdigest()
print(b)